plugins {
    id 'fml-loom' version '0.1'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

def useLocalizedArchiveName = Locale.default.country.equalsIgnoreCase("CN")

base {
    archivesName = useLocalizedArchiveName
            ? "[高亮信息显示]${project.archives_base_name}"
            : project.archives_base_name
}

repositories {
    maven {
        name = "Spongepowered"
        url = "https://repo.spongepowered.org/repository/maven-public/"
    }
    maven {
        name = "ModdedMITE"
        url = "https://maven.limingzxc.top/repository/maven-public/"
    }
}

configurations {
    fml
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "it.unimi.dsi:fastutil:8.5.12"
    implementation "com.google.code.gson:gson:2.11.0"

    fml "com.github.MinecraftIsTooEasy:FishModLoader:3.4.2"
    implementation "com.github.MinecraftIsTooEasy:FishModLoader:3.4.2"

    implementation "com.github.MinecraftIsTooEasy:ManyLib:2.3.0"
    implementation "com.github.MinecraftIsTooEasy:ModMenu:10.1.1"

    compileOnly "com.github.MinecraftIsTooEasy:EMI:1.1.27"
    localRuntime "com.github.MinecraftIsTooEasy:EMI:1.1.27"
}

def fmlResolvedFile = configurations.fml.singleFile

loom {
    accessWidenerPath = file("src/main/resources/waila.accesswidener")
    mergedMinecraftJar()
    setFML(fmlResolvedFile)
    dependencies.add("mappings", fmlMCPMappings())
    mods {
        "waila" {
            sourceSet sourceSets.main
        }
    }
    runs {
        client {
            String name = project.username
            String width = project.screen_width
            String height = project.screen_height
            programArgs "--userProperties", "{}", "--username", name, "--session", "a.a.a.a", "--width", width, "--height", height
        }
    }
}

processResources {
    inputs.properties(
            version: project.version,
            id: project.mod_id,
            name: project.mod_name
    )

    filesMatching("fml.mod.json") {
        expand(inputs.properties)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { String fileName -> "${fileName}_${inputs.properties.archivesName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.maven_id
            from(components.java)
        }
    }

    repositories {
        maven {
            name = "ModdedMITE"
            url = uri("https://maven.limingzxc.top/repository/maven-releases/")
            credentials {
                // Read only from gradle.properties (user level, your gradle_home)
                username = project.findProperty("nexusUsername")
                password = project.findProperty("nexusPassword")
            }
        }
    }
}
